# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=false
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=false
org.gradle.configuration-cache=false
ksp.incremental=false
android.disallowKotlinSourceSets=false
googleServices.missing.passthrough=true
