# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=false
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=false
org.gradle.configuration-cache=false
ksp.incremental=false
ksp.use.ksp2=true
googleServices.missing.passthrough=true
